# Generated by Django 4.2.2 on 2023-07-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('profile_photo', models.ImageField(upload_to='')),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('approx_followers', models.SmallIntegerField()),
                ('age', models.SmallIntegerField()),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Waiting for the one', 'Searching')], default='Single', max_length=100)),
                ('bust', models.SmallIntegerField()),
                ('waist', models.SmallIntegerField()),
                ('hip', models.SmallIntegerField()),
                ('height_feet', models.SmallIntegerField()),
                ('height_inches', models.SmallIntegerField()),
                ('weight', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='model_assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teen', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('milf', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('hot', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('sexy', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('nerdy', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('summer_body', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('fat', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('aunty', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('redhead', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('petite', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('pretty', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('goddess', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('bigboobs', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('bigass', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('classy', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('topper', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('naughty', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('asshole', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('playgirl', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('creep', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('gamer', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('animelover', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('movielover', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('reader', models.BooleanField(choices=[(1, 'No'), (2, 'Yes')], default=1)),
                ('model_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spymain.models_info')),
            ],
        ),
    ]
