# Generated by Django 4.2.2 on 2023-07-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spymain', '0002_models_info_hobbies_models_info_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_assets',
            name='animelover',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='asshole',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='aunty',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='bigass',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='bigboobs',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='classy',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='creep',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='fat',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='gamer',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='goddess',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='hot',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='milf',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='movielover',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='naughty',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='nerdy',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='petite',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='playgirl',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='pretty',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='reader',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='redhead',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='sexy',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='summer_body',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='teen',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='topper',
            field=models.BooleanField(blank=True, choices=[(1, 'No'), (2, 'Yes')], null=True),
        ),
    ]
