# Generated by Django 4.2.2 on 2023-07-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spymain', '0003_alter_model_assets_animelover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_assets',
            name='animelover',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='asshole',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='aunty',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='bigass',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='bigboobs',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='classy',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='creep',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='fat',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='gamer',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='goddess',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='hot',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='milf',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='movielover',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='naughty',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='nerdy',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='petite',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='playgirl',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='pretty',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='reader',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='redhead',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='sexy',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='summer_body',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='teen',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_assets',
            name='topper',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
    ]
