# Generated by Django 4.2.2 on 2023-07-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spymain', '0005_alter_models_info_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_assets',
            old_name='model_username',
            new_name='model',
        ),
    ]
