# Generated by Django 4.2.2 on 2023-07-01 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Spymain', '0006_rename_model_username_model_assets_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_assets',
            name='Username',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
