# Generated by Django 3.2 on 2023-07-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spymain', '0007_model_assets_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_info',
            name='profile_photo',
            field=models.ImageField(upload_to='media/uploads'),
        ),
    ]
