# Generated by Django 3.2 on 2023-07-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spymain', '0010_alter_models_info_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_info',
            name='profile_photo',
            field=models.ImageField(upload_to='uploads/profilephoto'),
        ),
    ]
