# Generated by Django 3.2 on 2023-07-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spymain', '0013_auto_20230709_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_info',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
