# Generated by Django 3.2 on 2023-07-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spymain', '0014_alter_models_info_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_info',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
